<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Perry de Valpine">
<meta name="dcterms.date" content="2021-10-29">

<title>A close look at some posted trials of nimble for accelerated failure time models – NIMBLE</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-cf518878a5773d5a4aca37031544c633.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-J6VLDBN5DK"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-J6VLDBN5DK', { 'anonymize_ip': true});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../blog/index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/nimble-logo-oval-small-clean.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../what-is-nimble.html"> 
<span class="menu-text">What is NIMBLE?</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../examples.html"> 
<span class="menu-text">Examples</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../documentation.html"> 
<span class="menu-text">Documentation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../download.html"> 
<span class="menu-text">Download</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../groups-and-issues.html"> 
<span class="menu-text">Community</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-blog" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Blog</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-blog">    
        <li>
    <a class="dropdown-item" href="../blog/index.html">
 <span class="dropdown-text">All Posts</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Recent Posts</li>
        <li>
    <a class="dropdown-item" href="../blog/version-1-4-1-of-nimble-released.html">
 <span class="dropdown-text">Version 1.4.1 Released</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../blog/nimbleQuad.html">
 <span class="dropdown-text">Using nimbleQuad for maximum likelihood estimation and deterministic posterior approximation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../blog/derived-quantities.html">
 <span class="dropdown-text">Using derived quantities in NIMBLE’s MCMC system</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../blog/version-1-4-0-of-nimble-released.html">
 <span class="dropdown-text">Version 1.4.0 and nimbleQuad Released</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../blog/announcing-the-nimblemacros-package-and-the-use-of-macros-in-nimble-models.html">
 <span class="dropdown-text">nimbleMacros Package</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">More</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more">    
        <li>
    <a class="dropdown-item" href="../contributing.html">
 <span class="dropdown-text">How to Contribute</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../release-notes.html">
 <span class="dropdown-text">Release Notes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../license-and-citation.html">
 <span class="dropdown-text">License and Citation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../about-us.html">
 <span class="dropdown-text">About Us</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools tools-wide">
    <a href="https://github.com/nimble-dev/nimble" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
    <a href="https://twitter.com/R_nimble" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-twitter"></i></a>
    <a href="../blog/index.xml" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-rss"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">A close look at some posted trials of nimble for accelerated failure time models</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Blog Posts</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../blog/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">All Posts</span></a>
  </div>
</li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="sidebar-item">
 <span class="menu-text">Recent Posts</span>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../blog/version-1-4-1-of-nimble-released.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Version 1.4.1 of NIMBLE released</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../blog/nimbleQuad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Using nimbleQuad for maximum likelihood estimation and deterministic posterior approximation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../blog/derived-quantities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Using derived quantities in NIMBLE’s MCMC system</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../blog/version-1-4-0-of-nimble-released.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Version 1.4.0 of NIMBLE released, plus new quadrature-based functionality in nimbleQuad package</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../blog/announcing-the-nimblemacros-package-and-the-use-of-macros-in-nimble-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">announcing the nimbleMacros package and the use of macros in NIMBLE models</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#accelerated-failure-time-aft-models" id="toc-accelerated-failure-time-aft-models" class="nav-link active" data-scroll-target="#accelerated-failure-time-aft-models">Accelerated Failure Time (AFT) models</a>
  <ul class="collapse">
  <li><a href="#right-censored-failure-time-data" id="toc-right-censored-failure-time-data" class="nav-link" data-scroll-target="#right-censored-failure-time-data">Right-censored failure time data</a></li>
  <li><a href="#bfgs-scenarios" id="toc-bfgs-scenarios" class="nav-link" data-scroll-target="#bfgs-scenarios">BFG’s scenarios</a></li>
  </ul></li>
  <li><a href="#some-issues-to-explore" id="toc-some-issues-to-explore" class="nav-link" data-scroll-target="#some-issues-to-explore">Some issues to explore</a></li>
  <li><a href="#setting-up-the-example" id="toc-setting-up-the-example" class="nav-link" data-scroll-target="#setting-up-the-example">Setting up the example</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A close look at some posted trials of nimble for accelerated failure time models</h1>
  <div class="quarto-categories">
    <div class="quarto-category">tutorial</div>
    <div class="quarto-category">R</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Perry de Valpine </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 29, 2021</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>A bunch of folks have brought to our attention a <a href="https://arxiv.org/abs/2107.09357">manuscript by Beraha, Falco and Guglielmi (BFG) posted on arXiv</a> giving some comparisons between JAGS, NIMBLE, and Stan. Naturally, we wanted to take a look. Each package performs best in some of their comparisons. There’s a lot going on, so here we’re just going to work through the last of their four examples, an accelerated failure time (AFT) model, because that’s the one where NIMBLE looks the worst in their results. The code from BFG is given on GitHub <a href="https://github.com/daniele-falco/software_comparison">here</a>.</p>
<p>There may be some issues with their other three examples as well, and we might work through those in future blog post(s). NIMBLE provides a lot of flexibility for configuring MCMCs in different ways (with different samplers), which means a comparison using our default configuration is just a start. Performance differences can also arise from writing the same model in different ways. We see both kinds of issues coming up for the other examples. But the AFT example gives a lot to talk about, so we’re sticking to that one here.</p>
<p>It turns out that NIMBLE and JAGS were put at a huge disadvantage compared to Stan, and that BFG’s results from NIMBLE don’t look valid, and that there isn’t any exploration of NIMBLE’s configurability. If we make the model for NIMBLE and JAGS comparable to the model for Stan, NIMBLE does roughly 2-45 times better in various cases than what BFG reported. If we explore a simple block sampling option, NIMBLE gets a small additional boost in some cases. It’s hard to compare results exactly with what BFG report, and we are not out to re-run the full comparison including JAGS and Stan. A “back of the envelope” comparison suggests that NIMBLE is still less efficient than Stan for this example, but not nearly to the degree reported. We’re also not out to explore many sampling configurations to try for better performance in this particular example problem, but part of NIMBLE’s design is to make it easy to do so.</p>
<p>Before starting into the AFT models, it’s worth recognizing that software benchmarks and other kinds of performance comparisons are really hard to do well. It’s almost inevitable that, when done by developers of one package, that package gets a boost in results even if objectivity is the honest goal. That’s because package developers almost can’t help using their package effectively and likely don’t know how to use other packages as well as their own. In this case, it’s fair to point out that NIMBLE needs more care in providing valid initial values (which BFG’s code doesn’t do) and that NIMBLE’s default samplers don’t work well here, which is because this problem features heavy right tails of Weibull distributions with shape parameter &lt; 1. For many users, that is not a typical problem. By choosing slice samplers (which JAGS often uses too) instead of NIMBLE’s default Metropolis-Hastings samplers, the mixing is much better. This issue is only relevant to the problem as BFG formulated it for JAGS and NIMBLE and goes away when we put it on par with the formulation BFG gave to Stan. In principle, comparisons by third parties, like BFG, might be more objective than those by package developers, but in this case the comparisons by BFG don’t use JAGS or NIMBLE effectively and include incorrect results from NIMBLE.</p>
<p>Below we try to reproduce their (invalid) results for NIMBLE and to run some within-NIMBLE comparisons of other methods. We’ll stick to their model scenarios and performance metrics. Those metrics are not the way we’ve done some published MCMC comparisons <a href="https://link.springer.com/article/10.1007/s10651-016-0353-z">here</a>, <a href="https://doi.org/10.1002/ece3.6053">here</a> and <a href="https://doi.org/10.1002/ecs2.3385">here</a>, but using them will allow readers to interpret our results alongside theirs.</p>
<p>First we’ll give a brief summary of their model scenarios. Here goes.</p>
<section id="accelerated-failure-time-aft-models" class="level1">
<h1>Accelerated Failure Time (AFT) models</h1>
<p>Here’s a lightning introduction to AFT models based on Weibull distributions. These are models for time-to-event data such as a “failure.” For shape <span class="math inline">\(a\)</span> and scale <span class="math inline">\(s\)</span>, the Weibull probability density function for time <span class="math inline">\(t\)</span> is</p>
<p><span class="math display">\[f_W(t | a, s) = \frac{a}{s}\left(\frac{t}{s}\right)^{a-1} e^{-\left(\frac{t}{s}\right)^a}\]</span></p>
<p>One important thing about the Weibull is that its cumulative density can be written in closed form. It is:</p>
<p><span class="math display">\[F_W(t | a, s) = 1-e^{\left(\frac{t}{s}\right)^a}\]</span></p>
<p>The role of covariates is to accelerate or decelerate the time course towards failure, effectively stretching or shrinking the time scale for each item. Specifically, for covariate vector <span class="math inline">\(x\)</span> and coefficient vector <span class="math inline">\(\eta\)</span>, define <span class="math inline">\(\theta = e^{-x' \eta}\)</span>. Then the distribution of times-to-event is defined by rescaling the Weibull: <span class="math inline">\(f(t | \theta, a, s) = \theta f_W(\theta t | a, s)\)</span>. This gives a Weibull with shape <span class="math inline">\(a\)</span> and scale <span class="math inline">\(s / \theta\)</span>, so we have</p>
<p><span class="math display">\[f(t | \theta, a, s) = f_W\left(t | a, \frac{s}{\theta}\right)\]</span></p>
<p>In the code, there are two parameterizations in play. The first is <span class="math inline">\((a, s)\)</span> as just given. This is used in Stan and could be used in NIMBLE because it supports alternative parameterizations, including that one. Given <span class="math inline">\(\eta\)</span>, the scale is <span class="math inline">\(\log(2)^{-\frac{1}{a}} e^{x' \eta}\)</span>. The second is <span class="math inline">\(\left(a, \lambda = \left(\frac{1}{s}\right)^{a}\right)\)</span>. This is the parameterization in the BUGS model language, so it is used in JAGS and is the default in NIMBLE. Given <span class="math inline">\(\eta\)</span>, <span class="math inline">\(\lambda = \log(2) e^{-a(x' \eta)}\)</span>.</p>
<p>The reason for the <span class="math inline">\(\log(2)\)</span> is that it makes the median of <span class="math inline">\(f_W(t | a, s)\)</span> be 1 for any <span class="math inline">\(a\)</span>, i.e.&nbsp;when <span class="math inline">\(x' \eta = 0\)</span>. Priors are put on <span class="math inline">\(a\)</span> (<code>alpha</code> in the code) and <span class="math inline">\(\eta\)</span> (<code>beta</code>). There is no separate scale parameter. Rather, <span class="math inline">\(\lambda = \log(2)\)</span> when <span class="math inline">\(x' \eta = 0\)</span>. The models are equivalent with either parameterization, and they shouldn’t have much impact on computational efficiency. We’re just pointing them out to follow what’s going on.</p>
<section id="right-censored-failure-time-data" class="level2">
<h2 class="anchored" data-anchor-id="right-censored-failure-time-data">Right-censored failure time data</h2>
<p>When a failure time is directly observed, its likelihood contribution is <span class="math inline">\(f_W(t | a, s e^{x' \eta})\)</span>. When a unit hasn’t failed by its last observation, all that is known is that it lasted at least until <span class="math inline">\(t\)</span>. Then its likelihood contribution is <span class="math inline">\(1-F_W(t | a, s e^{x' \eta})\)</span>. This is called a right-censored observation. Thus the data consist of some <span class="math inline">\(t\)</span>s that are actual failure times and some <span class="math inline">\(t\)</span>s that are right-censoring times.</p>
<p>There are two ways to handle a right-censored observation in MCMC:</p>
<ul>
<li>Include the likelihood factor <span class="math inline">\(1-F_W(t | a, s e^{x' \eta})\)</span>. This is how BFG set up the model for Stan.</li>
<li>Include a latent state, <span class="math inline">\(t'\)</span>, for the failure time. Include the likelihood factor <span class="math inline">\(f_W(t' | a, s e^{x' \eta})\)</span> and let MCMC sample <span class="math inline">\(t'\)</span>, with the numerical effect of integrating over it. This is how BFG set up the model for JAGS and NIMBLE.</li>
</ul>
<p>The first version is marginalized relative to the second version because <span class="math inline">\(1-F_W(t | a, s e^{x' \eta})\)</span> integrates over <span class="math inline">\(t'\)</span> without needing to sample it. Often, but not always, marginalization is computationally faster and gives better mixing, so it makes the MCMC problem easier. That’s why the comparison as set up by BFG seems like an apples-to-oranges comparison. They’ve made the problem substantially easier for Stan.</p>
<p>It’s easy to set up the marginalized version for JAGS or NIMBLE. This can be done using the “zeroes” trick in the BUGS language, which both packages use for writing models. In NIMBLE this can also be done by writing a user-defined distribution as a <code>nimbleFunction</code>, which can be compiled along with a model.</p>
</section>
<section id="bfgs-scenarios" class="level2">
<h2 class="anchored" data-anchor-id="bfgs-scenarios">BFG’s scenarios</h2>
<p>BFG included the following scenarios:</p>
<ul>
<li>Sample size, <span class="math inline">\(N\)</span>, is 100 or 1000.</li>
<li>Number of explanatory variables, <span class="math inline">\(p\)</span>, is 4 or 16. These always include an intercept. Other covariates, and the true coefficient values, are simulated.</li>
<li>Censoring times are drawn from another Weibull distribution. This is set up following previous works such that the expected proportion of censored values is 20%, 50% or 80%.</li>
<li>Most of their comparisons use informative priors. Those are the ones we look at here. Again, we weren’t out to look at everything they did.</li>
<li>They used <span class="math inline">\(N_{it} = 10,000\)</span> total iterations. Of these, <span class="math inline">\(5,000\)</span> were discarded as burn-in (warmup). They used a thinning interval of 2, resulting in <span class="math inline">\(N_s = 2,500\)</span> saved samples.</li>
</ul>
</section>
</section>
<section id="some-issues-to-explore" class="level1">
<h1>Some issues to explore</h1>
<p>Now that we’ve set up the background, we are ready to list some of the issues with BFG’s comparisons that are worth exploring. For the computational experiments below, we decided to limit our efforts to NIMBLE because we are not trying to re-do BFG’s full analysis. Here are the main issues.</p>
<ol type="1">
<li><strong>BFG gave Stan a much easier problem than they gave JAGS and NIMBLE.</strong> Stan was allowed to use direct calculation of right-censored probabilities. These are complementary (right-tail) cumulative probability density calculations. NIMBLE and JAGS were made to sample latent failure times for censored items, even though they can be set up to use the cumulative calculations as well. Below we give NIMBLE a more comparable problem to the one given by BFG to Stan.</li>
<li><strong>It looks like BFG must not have obtained valid results from NIMBLE because they did not set up valid initial values for latent failure times.</strong> NIMBLE can be more sensitive to initial values (“inits”) than JAGS. We think that’s partly because NIMBLE uses a lot of adaptive random-walk Metropolis-Hastings samplers in its default MCMC configuration. In any case, NIMBLE gives warnings at multiple steps if a user should give attention to initial values. We give warnings instead of errors because a user might have plans to add initial values at a later step, and because sometimes MCMC samplers can recover from bad initial values. In the AFT example, the model does not “know” that initial values for latent failure times must be greater than the censoring times. If they aren’t, the likelihood calculations will return a <code>-Inf</code> (or possibly <code>NA</code>), which causes trouble for the samplers. Inspection of the model after MCMC runs using BFG’s code shows that even after 10000 iterations, the model likelihood is <code>-Inf</code>, so the results are invalid. It’s fair to say this is an issue in how to use NIMBLE, but it’s confusing to include invalid results in a comparison.</li>
<li><strong>Even with valid initial values in BFG’s model formulation, NIMBLE’s default samplers do not do well for this example. In this post, we explore slice samplers instead.</strong> The problem is that the Weibull distributions in these scenarios give long right tails, due to simulating with shape parameter &lt; 1. This corresponds to failure rates that decrease with time, like when many failures occur early and then those that don’t fail can last a long, long time. MCMC sampling of long right tails is a known challenge. In trial runs, we saw that, to some extent, the issue can be diagnosed by monitoring the latent failure times and noticing that they don’t mix well. We also saw that sometimes regression parameters displayed mixing problems. BFG report that NIMBLE’s results have mean posterior values farther from the correct values than given by the other tools, which is a hint that something is more deeply wrong. Slice samplers work much better for this situation, and it is easy to tell NIMBLE to use slice samplers, which we did.</li>
<li><strong>BFG’s code uses matrix multiplication for <code>X%*%eta</code> in Stan, but not in NIMBLE or JAGS, even though they also support matrix multiplication.</strong> Instead, BFG’s code for NIMBLE and JAGS has a scalar declaration for each element of the matrix multiplication operation, followed by the sums that form each element of the result. We modify the code to use matrix multiplication. While we don’t often see this make a huge difference in run-time performance (when we’ve looked at the issue in other examples), it could potentially matter, and it definitely speeds up NIMBLE’s model-building and compilation steps because there is less to keep track of. An intermediate option would be to use inner products (<code>inprod</code>).</li>
<li>It’s worth noting that <em>all of these examples are fairly fast and mix fairly well</em>. Some might disagree, but these all generate reasonable effective sample sizes in seconds-to-minutes, not hours-to-days.</li>
<li>There are some minor issues, and we don’t want to get nit-picky. One is that we don’t see BFG’s code being set up to be reproducible. For example, not only is there no <code>set.seed</code> so that others can generate identical data sets, but it looks like <em>each package was given different simulated data sets</em>. It can happen that MCMC performance depends on the data set. While this <em>might</em> not be a huge issue, we prefer below to give each package the same, reproducible, data sets. Another issue is that looking at <em>average</em> effective sample size across parameters can be misleading because one wants all parameters mixed well, not some mixed really well and others mixed poorly. But in these examples the parameters compared are all regression-type coefficients that play similar roles in the model, and the averaging doesn’t look like a huge issue. Finally, BFG decline to report ESS/time, preferring instead to report ESS and time and let readers make sense of them. We see ESS/time as the primary metric of interest, the number of effectively independent samples generated per second, so we report it below. This gives a way to see how both mixing (ESS) and computation time contribute to MCMC performance.</li>
</ol>
</section>
<section id="setting-up-the-example" class="level1">
<h1>Setting up the example</h1>
<p>We use BFG’s code but modify it to organize it into functions and make it reproducible. The <a href="https://github.com/nimble-dev/nimble-demos/tree/master/blog_posts/AFT_comparisons_Behara_etal">source files</a> for this document includes code chunks to run and save results. We are not running JAGS or Stan because we are not trying to reproduce a full set of comparisons. Instead we are looking into NIMBLE’s performance for this example. Since the main issue is that BFG gave NIMBLE and JAGS harder models than they gave Stan, we fix this in a way that is not NIMBLE-specific and should also work for JAGS.</p>
<p>Here is a summary of what the code does:</p>
<ul>
<li>Set up the twelve cases with informative priors included in the first twelve rows of BFG’s table 5, which has their AFT results.</li>
<li>For each of the twelve cases, run:
<ul>
<li>the original method of BFG, which gives <strong>invalid</strong> results but is useful for trying to see how much later steps improve over what BFG reported;</li>
<li>a method with valid initial values and slice sampling, but still in the harder model formulation given by BFG;</li>
<li>a method with the model formulation matching what BFG gave to Stan, using marginal probabilities for censored times and also using matrix multiplication;</li>
<li>a method with the model formulation matching what BFG gave to Stan and also with one simple experiment in block sampling. The block sampler used is a multivariate adaptive random-walk Metropolis-Hastings sampler for all the regression coefficients. It sometimes helps to let these try multiple propose-accept/reject steps because otherwise <span class="math inline">\(p\)</span> tries are replaced with 1 try (where <span class="math inline">\(p\)</span>) is the number of regression coefficients). As a heuristic choice, we used <span class="math inline">\(p/2\)</span> tries each time the sampler ran.</li>
</ul></li>
</ul>
<p>Although the original method of BFG seems to give invalid results, we include it so we can try to roughly compare performance (shown below) against what they report. However one difficulty is that processing with <code>-Inf</code> and <code>NaN</code> values can be substantially slower than processing with actual numbers, and these issues might differ across systems.</p>
<p>Results here are run on a MacBook Pro (2019), with 2.4 GHz 8-Core Intel Core i9, and OS X version 11.6.</p>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<p>Here are the results, in a table that roughly matches the format of BFG’s Table 5. “Perc” is the average fraction of observations that are right-censored.</p>
<p>As best as we can determine:</p>
<ul>
<li>“ESS/Ns” is their “ε_η”. This is the mean effective sample size of the (4 or 16) beta coefficients per saved MCMC iteration. The number of saved iterations, N_s is 2500. We used <code>coda::effectiveSize</code> to estimate ESS. We did not see in their code what method they used. This is another reason we can’t be sure how to compare our results to theirs.</li>
<li>“Nit/t” is their “N_it/t_s”, total number of iterations (10000) per computation time, not counting compilation time.</li>
<li>We calculate “ESS/t”, which is the product of the previous two numbers divided by four, (ESS/Ns)*(Nit/t)/4. This is the mean effective sample size from the saved samples per total sampling time (including burn-in). One might also consider modifying this for the burn-in portion. The factor 4 comes from N_it/N_s = 4. We do it this way to make it easier to compare to BFG’s Table 5. They decline to calculate a metric of ESS per time, which we view as a fundamental metric of MCMC performance. An MCMC can be efficient either by generating well-mixed samples at high computational cost or generating poorly-mixed samples at low computational cost, so both mixing and computational cost contribute to MCMC efficiency.</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;"></th>
<th style="text-align: right;">BFG (invalid)</th>
<th style="text-align: right;"></th>
<th style="text-align: right;"></th>
<th style="text-align: right;">BFG+inits+slice</th>
<th style="text-align: right;"></th>
<th style="text-align: right;"></th>
<th style="text-align: right;">Marginal</th>
<th style="text-align: right;"></th>
<th style="text-align: right;"></th>
<th style="text-align: right;">Marginal+blocks</th>
<th style="text-align: right;"></th>
<th style="text-align: right;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: right;">ESS/Ns</td>
<td style="text-align: right;">Nit/t</td>
<td style="text-align: right;">ESS/t</td>
<td style="text-align: right;">ESS/Ns</td>
<td style="text-align: right;">Nit/t</td>
<td style="text-align: right;">ESS/t</td>
<td style="text-align: right;">ESS/Ns</td>
<td style="text-align: right;">Nit/t</td>
<td style="text-align: right;">ESS/t</td>
<td style="text-align: right;">ESS/Ns</td>
<td style="text-align: right;">Nit/t</td>
<td style="text-align: right;">ESS/t</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Perc = 0.2</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">N=100, p = 4, perc = 0.2</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">6844.63</td>
<td style="text-align: right;">465.80</td>
<td style="text-align: right;">0.52</td>
<td style="text-align: right;">2325.58</td>
<td style="text-align: right;">300.65</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">9775.17</td>
<td style="text-align: right;">951.09</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">16233.77</td>
<td style="text-align: right;">1109.06</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">N=1000, p = 4, perc = 0.2</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">1127.27</td>
<td style="text-align: right;">84.71</td>
<td style="text-align: right;">0.55</td>
<td style="text-align: right;">306.22</td>
<td style="text-align: right;">41.83</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: right;">1527.88</td>
<td style="text-align: right;">157.65</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">2490.04</td>
<td style="text-align: right;">171.47</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">N=100, p = 16, perc = 0.2</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">3423.49</td>
<td style="text-align: right;">161.60</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: right;">949.49</td>
<td style="text-align: right;">84.94</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">3717.47</td>
<td style="text-align: right;">248.99</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">5621.14</td>
<td style="text-align: right;">408.77</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">N=1000, p = 16, perc = 0.2</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">404.22</td>
<td style="text-align: right;">7.80</td>
<td style="text-align: right;">0.57</td>
<td style="text-align: right;">98.86</td>
<td style="text-align: right;">14.16</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: right;">591.82</td>
<td style="text-align: right;">61.12</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">1100.47</td>
<td style="text-align: right;">83.33</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Perc = 0.5</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">N=100, p = 4, perc = 0.5</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">7262.16</td>
<td style="text-align: right;">98.39</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">2572.68</td>
<td style="text-align: right;">54.45</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">10214.50</td>
<td style="text-align: right;">960.31</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">15060.24</td>
<td style="text-align: right;">990.34</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">N=1000, p = 4, perc = 0.5</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">1106.32</td>
<td style="text-align: right;">26.96</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">298.23</td>
<td style="text-align: right;">7.25</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">1987.28</td>
<td style="text-align: right;">219.92</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">3074.09</td>
<td style="text-align: right;">196.19</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">N=100, p = 16, perc = 0.5</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">3411.80</td>
<td style="text-align: right;">52.07</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">940.56</td>
<td style="text-align: right;">49.94</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">3955.70</td>
<td style="text-align: right;">229.94</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">5854.80</td>
<td style="text-align: right;">415.89</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">N=1000, p = 16, perc = 0.5</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">339.29</td>
<td style="text-align: right;">5.88</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">95.90</td>
<td style="text-align: right;">1.66</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: right;">601.90</td>
<td style="text-align: right;">61.98</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">1074.58</td>
<td style="text-align: right;">83.07</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Perc = 0.8</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">N=100, p = 4, perc = 0.8</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">6761.33</td>
<td style="text-align: right;">51.99</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">2297.79</td>
<td style="text-align: right;">10.79</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">9842.52</td>
<td style="text-align: right;">602.28</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">15151.52</td>
<td style="text-align: right;">763.36</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">N=1000, p = 4, perc = 0.8</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">1013.27</td>
<td style="text-align: right;">5.16</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">265.58</td>
<td style="text-align: right;">1.50</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">1831.50</td>
<td style="text-align: right;">180.50</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">2856.33</td>
<td style="text-align: right;">176.27</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">N=100, p = 16, perc = 0.8</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">3412.97</td>
<td style="text-align: right;">33.45</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">876.96</td>
<td style="text-align: right;">6.74</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">3853.56</td>
<td style="text-align: right;">166.26</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">5820.72</td>
<td style="text-align: right;">329.18</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">N=1000, p = 16, perc = 0.8</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">395.99</td>
<td style="text-align: right;">1.22</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">95.33</td>
<td style="text-align: right;">1.22</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">560.54</td>
<td style="text-align: right;">54.91</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">1016.57</td>
<td style="text-align: right;">72.55</td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<p>The left-most set of results (“BFG (invalid)”) is comparable to the right-most (“NIMBLE”) column of BFG’s Table 5, in the same row order for their first 12 rows. The simulated data sets are different. For that reason and the stochasticity of Monte Carlo methods, we shouldn’t expect to see exactly matching values. And of course the computations were run on different systems, resulting in different times. Again, these results are <strong>invalid</strong>.</p>
<p>The next column (“BFG+inits+slice”) gives results when BFG’s model formulation for JAGS and NIMBLE is combined with valid initialization and slice sampling in NIMBLE. We can see that valid sampling generally gives lower ESS/time than the invalid results.</p>
<p>The next column shows results when the problem is set up as BFG gave it to Stan, and NIMBLE’s default samplers are used. If we assume the left-most results are similar to what BFG report, but with times from the system used here, then the boost in performance is the ratio of ESS/time between methods. For example, in the last row, the marginal method is 54.91/1.22 = 45.01 times more efficient that what BFG reported. We can make a similar kind of ratio between Stan and NIMBLE from BFG’s results, which gave Stan as about 380 times more efficient than NIMBLE (although rounding error for “1%” could be a substantial issue here). Putting these together, Stan might really be about 8.4 times more efficient than NIMBLE for this case, which is the hardest case considered.</p>
<p>The last column shows results of the single experiment with alternative (block) samplers that we tried. In many cases, it gives a modest additional boost. Often with more work one can find a better sampling strategy, which can be worth the trouble for extended work with a particular kind of model. In the last row of our results, this gives about another 72.55 / 54.91 = 1.32 boost in performance, lowering the ratio to Stan to about 6.4. Again, we decided to limit this post to within-NIMBLE comparisons, and the comparisons to Stan based on BFG’s results should be taken with a grain of salt because we didn’t re-run them.</p>
<p>In summary, it looks like BFG gave Stan a different and easier accelerated failure time problem than they gave NIMBLE and JAGS. When given the same problem as they gave Stan, NIMBLE’s default samplers perform around 2 to 45 times better than what BFG reported.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/r-nimble\.org");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>