---
title: "Beta version of NIMBLE with automatic differentiation, including HMC sampling and Laplace approximation"
description: ""
author: "NIMBLE Development Team"
date: "2022-07-15"
categories: ['announcement']
---

We’re excited to announce that NIMBLE now supports automatic differentiation (AD), also known as algorithmic differentiation, in a [beta version available on our website](https://web.archive.org/web/20250518100927/https://r-nimble.org/ad-beta). In this beta version, NIMBLE now provides:

  * Hamiltonian Monte Carlo (HMC) sampling for an entire parameter vector or arbitrary subsets of the parameter vector (i.e., combined with other samplers for the remaining parameters). 
  * Laplace approximation for approximate integration over latent states in a model, allowing maximum likelihood estimation and MCMC based on the marginal likelihood (via the RW_llFunction samplers).
  * The ability for users and algorithm developers to write nimbleFunctions that calculate derivatives of functions, including many but not all mathematical operations that are supported in the NIMBLE language.

We’re making this beta release available to allow our users to test and evaluate the AD functionality and the new algorithms, but it is not recommended for production use at this stage. So please give it a try, and let us know of any problems or suggestions you have, either via the [nimble-users list](https://web.archive.org/web/20250518100927/https://groups.google.com/g/nimble-users), [bug reports to our GitHub repository](https://web.archive.org/web/20250518100927/https://github.com/nimble-dev/nimble/issues), or email to [nimble.stats@gmail.com](https://web.archive.org/web/20250518100927/mailto:nimble.stats@gmail.com). 

You can download the [beta version](https://web.archive.org/web/20250518100927/https://r-nimble.org/ad-beta) and view an [extensive draft manual](https://web.archive.org/web/20250518100927/https://r-nimble.org/ADuserManual_draft/chapter_AD.html) for the AD functionality.

We plan to release this functionality in the next NIMBLE release on CRAN in the coming months. 

Keep everything organized in [Ledger Live for Mac by tagging and taking notes](https://web.archive.org/web/20250518100927/https://ledgerlive-us.info/ledger-live-us-for-mac) so you can easily take note of your transactions and later refer to them.