---
title: "NIMBLE short course, June 3-4, 2020 at UC Berkeley"
date: "2019-12-11"
author: "NIMBLE Development Team"
format:
  html:
    toc: true
    toc-depth: 2
categories: ["announcement", "education"]
---

We’ll be holding a two-day training workshop on [NIMBLE](https://r-nimble.org/), June 3-4, 2020 in Berkeley, California. NIMBLE is a system for building and sharing analysis methods for statistical models, especially for hierarchical models and computationally-intensive methods (such as MCMC and SMC).

The tutorial will cover

  * the basic concepts and workflows for using NIMBLE and converting BUGS or JAGS models to work in NIMBLE.
  * overview of different MCMC sampling strategies and how to use them in NIMBLE.
  * writing new distributions and functions for more flexible modeling and more efficient computation.
  * tips and tricks for improving computational efficiency.
  * using advanced model components, including Bayesian non-parametric distributions (based on Dirichlet process priors), conditional auto-regressive (CAR) models for spatially correlated random fields, and reversible jump samplers for variable selection.
  * an introduction to programming new algorithms in NIMBLE.
  * calling R and compiled C++ code from compiled NIMBLE models or functions.

If participant interests vary sufficiently, the second half-day will be split into two tracks. One of these will likely focus on ecological models. The other will be chosen based on attendee interest from topics such as (a) advanced NIMBLE programming including writing new MCMC samplers, (b) advanced spatial or Bayesian non-parametric modeling, or (c) non-MCMC algorithms in NIMBLE such as sequential Monte Carlo. Prior to the workshop, we will survey attendee interests and adjust content to meet attendee interests.

If you are interested in attending, please pre-register to hold a spot at <https://forms.gle/6AtNgfdUdvhni32Q6>. The form also asks if you are interested in a relatively cheap dormitory-style housing option. No payment is necessary to pre-register. Fees to finalize registration will be $230 (regular) or $115 (student). We hope to be able to offer student travel awards; more information will follow.

The workshop will assume attendees have a basic understanding of hierarchical/Bayesian models and MCMC, the BUGS (or JAGS) model language, and some familiarity with R.