---
title: "NIMBLE webinar Friday April 13"
date: "2018-03-20"
author: "Chris Paciorek"
format:
  html:
    toc: true
    toc-depth: 2
categories: ["announcement","education"]
---

We’ll be presenting a webinar on NIMBLE, hosted by the Eastern North America Region of the International Biometric Society. Details are as follows.

**Programming with hierarchical statistical models: An introduction to the BUGS-compatible NIMBLE system for MCMC and more**

Friday, April 13, 2018

11:00 a.m. – 1:00 p.m. EST

Must register before April 12. You can register [here](https://portal.enar.org/Events/SelectRegType.aspx?EventCode=WEB041318). (You’ll need to create an account on the ENAR website and there is a modest fee – from $25 for ENAR student members up through $85 for non-IBS members.)

This webinar will introduce attendees to the NIMBLE system for programming with hierarchical models in R. NIMBLE ([r-nimble.org](http://r-nimble.org/)) is a system for flexible programming and dissemination of algorithms that builds on the BUGS language for declaring hierarchical models. NIMBLE provides analysts with a flexible system for using MCMC, sequential Monte Carlo and other techniques on user-specified models. It provides developers and methodologists with the ability to write algorithms in an R-like syntax that can be easily disseminated to users. C++ versions of models and algorithms are created for speed, but these are manipulated from R without any need for analysts or algorithm developers to program in C++.

While analysts can use NIMBLE as a drop-in replacement for WinBUGS or JAGS, NIMBLE provides greatly enhanced functionality in a number of ways. The webinar will first show how to specify a hierarchical statistical model using BUGS syntax (including user-defined function and distributions) and fit that model using MCMC (including user customization for better performance). We will demonstrate the use of NIMBLE for biostatistical methods such as semiparametric random effects models and clustering models. We will close with a discussion of how to use the system to write algorithms for use with hierarchical models, including building and disseminating your own methods.

**Presenter:**

Chris Paciorek

Adjunct Professor, Statistical Computing Consultant

Department of Statistics, University of California, Berkeley