---
title: "Version 0.7.0 of NIMBLE released"
date: "2019-02-05"
author: "NIMBLE Development Team"
format:
  html:
    toc: true
    toc-depth: 2
categories: ['release', 'announcement']
---

We’ve released the newest version of NIMBLE on CRAN and on our [website](https://r-nimble.org/). NIMBLE is a system for building and sharing analysis methods for statistical models, especially for hierarchical models and computationally-intensive methods (such as MCMC and SMC). Version 0.7.0 provides a variety of new features, as well as various bug fixes.

New features include:

  * greatly improved efficiency of sampling for Bayesian nonparametric (BNP) mixture models that use the `dCRP` (Chinese Restaurant process) distribution;
  * addition of the double exponential (Laplace) distribution for use in models and nimbleFunctions;
  * a new `RW_wishart` MCMC sampler, for sampling non-conjugate Wishart and inverse-Wishart nodes;
  * handling of the normal-inverse gamma conjugacy for BNP mixture models using the dCRP distribution;
  * enhanced functionality of the `getSamplesDPmeasure` function for posterior sampling from BNP random measures with Dirichlet process priors.
  * handling of five-dimensional arrays in models;
  * enhanced warning messages; and
  * an [HTML version of the NIMBLE manual](https://r-nimble.org/documentation-2).

Please see the NEWS file in the installed package for more details.