---
title: "Version 0.6-6 of NIMBLE released!"
description: ""
author: "NIMBLE Development Team"
date: "2017-07-29"
categories: ['release', 'announcement']
---

We’ve just released the newest version of NIMBLE on CRAN and on our website. Version 0.6-6 has some important new features, and more are on the way in the next few months.

New features include:

  * dynamic indexes are now allowed in BUGS code — indexes of a variable no longer need to be constants but can be other nodes or functions of other nodes; for this release this is a beta feature that needs to be enabled with nimbleOptions(allowDynamicIndexing = TRUE);
  * the intrinsic Gaussian CAR (conditional autoregressive) model can now be used in BUGS code as dcar_normal, which behaves similarly to BUGS’ car.normal distribution;
  * optim is now part of the NIMBLE language and can be used in nimbleFunctions;
  * it is possible to call out to external compiled code or back to R functions from a nimbleFunction using nimbleExternalCall() and nimbleRcall() (this is an experimental feature);
  * the WAIC model selection criterion can be calculated using the calculateWAIC() method for MCMC objects;
  * the bootstrap and auxiliary particle filters can now return their ESS values;
  * and a variety of bug fixes.

Please see the NEWS file in the installed package for more details.

Finally, we’re deep in the midst of development work to enable automatic differentiation, Tensorflow as an alternative back-end computational engine, additional spatial models, and Bayesian nonparametrics.