---
title: "Version 1.0.1 of NIMBLE released, fixing a bug in version 1.0.0 affecting certain models"
description: ""
author: "NIMBLE Development Team"
date: "2023-06-21"
categories: ['release', 'announcement']
---

We’ve released the newest version of NIMBLE on CRAN and on our website. NIMBLE is a system for building and sharing analysis methods for statistical models, especially for hierarchical models and computationally-intensive methods (such as MCMC and SMC).

Version 1.0.1 follows shortly after 1.0.0 and fixes an issue and a bug introduced in version 1.0.0 causing data to be set incorrectly in certain models.

Both cases occur only when a variable (e.g., `x`) contains both stochastic nodes (e.g. `x[2] ~ <some distribution>`) and *either* deterministic nodes (e.g. `x[3] <- <some calculation>`) or right-hand-side-only nodes (e.g. `x[4]` appears only on the right-hand-side, like an explanatory value).

The issue involves a change of behavior (relative to previous nimble versions) when both setting data values for some nodes and initial values for other nodes within the same variable (that satisfies the previous condition). Data values for right-hand-side-only nodes were replaced by initial values (inits) if both were provided. Version 1.0.1 reverts to previous behavior that data values are not replaced by initial values in that situation.

The bug involves models where (for a variable satisfying the previous condition) not every scalar element within the variable is used as a node and some of the nodes in the variable are data. In that situation, data values may be set incorrectly. This could typically occur in models with autoregressive structure directly on some data nodes (such as may be the case for capture-recapture models involving many individual capture histories within the same variable, indexed by individual and time, with some individuals not present for the entire time series, resulting in unused scalar elements of the variable).

Please see the [release notes](https://r-nimble.org/more/news) on our website for more details.